### ISSUE TITLE
divine sacrifice

### ISSUE THREAD

**Issue by MissZay** [Zerf/hagakure_cooldown#1]
currently the addon displays a timer for the group wide damage redirection (https://wotlkdb.com/?spell=64205 which lasts 10 seconds) instead of the raid wide damage reduction (https://wotlkdb.com/?spell=70940 which lasts 6seconds) so it might be confusing for people if they're trying to chain dsacs together for the damage reduction

**Comment by Zerf** [comment]
Yeah, changed in code as most people care about raid part only.
